name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Compile the code
        run: |
          echo "Compiling the code..."
          echo "Compile complete."

  unit-test-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run unit tests
        run: |
          javac -d bin src/cosc202/andie/*.java
          javac -d bin -classpath bin:lib/junit-platform-console-standalone-1.8.2.jar src/test/cosc202/andie/*.java
          java -jar lib/junit-platform-console-standalone-1.8.2.jar -classpath bin --select-package test.cosc202.andie

  lint-test-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linting code
        run: |
          echo "Linting code... This will take about 10 seconds."
          sleep 10
          echo "No lint issues found."

  deploy-job:
    needs: [unit-test-job, lint-test-job]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploying application
        run: |
          echo "Deploying application..."
          echo "Application successfully deployed."

  pages:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Generate Javadoc and publish
        run: |
          javadoc -d docs src/cosc202/andie/*.java
          mkdir public
          echo 'test' > public/test.txt
          mv docs public/
          ls -R public | head
          echo 'first ten public/ files listed'
    outputs:
      public-folder: 'public'
